


public class calculadora extends javax.swing.JFrame {
        double PrimerNumero;
        double SegundoNumero;
        double Resultado;
        String Operador;
    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JTextField();
        btnSuma = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        N1 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        N2 = new javax.swing.JButton();
        N3 = new javax.swing.JButton();
        N6 = new javax.swing.JButton();
        N5 = new javax.swing.JButton();
        N4 = new javax.swing.JButton();
        N9 = new javax.swing.JButton();
        N8 = new javax.swing.JButton();
        N7 = new javax.swing.JButton();
        N0 = new javax.swing.JButton();
        btnLimp = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaActionPerformed(evt);
            }
        });
        getContentPane().add(Pantalla);
        Pantalla.setBounds(30, 50, 240, 50);

        btnSuma.setBackground(new java.awt.Color(51, 51, 51));
        btnSuma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(255, 255, 255));
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma);
        btnSuma.setBounds(210, 260, 60, 120);

        btnDiv.setBackground(new java.awt.Color(51, 51, 51));
        btnDiv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(255, 255, 255));
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiv);
        btnDiv.setBounds(210, 170, 60, 30);

        btnResta.setBackground(new java.awt.Color(51, 51, 51));
        btnResta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnResta.setForeground(new java.awt.Color(255, 255, 255));
        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnResta);
        btnResta.setBounds(210, 230, 60, 30);

        btnMult.setBackground(new java.awt.Color(51, 51, 51));
        btnMult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMult.setForeground(new java.awt.Color(255, 255, 255));
        btnMult.setText("*");
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });
        getContentPane().add(btnMult);
        btnMult.setBounds(210, 200, 60, 30);

        N1.setBackground(new java.awt.Color(0, 0, 0));
        N1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        N1.setForeground(new java.awt.Color(255, 255, 255));
        N1.setText("1");
        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });
        getContentPane().add(N1);
        N1.setBounds(30, 140, 60, 60);

        btnPunto.setBackground(new java.awt.Color(51, 51, 51));
        btnPunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPunto.setForeground(new java.awt.Color(255, 255, 255));
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPunto);
        btnPunto.setBounds(90, 320, 60, 60);

        btnIgual.setBackground(new java.awt.Color(51, 51, 51));
        btnIgual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        getContentPane().add(btnIgual);
        btnIgual.setBounds(150, 320, 60, 60);

        N2.setBackground(new java.awt.Color(0, 0, 0));
        N2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        N2.setForeground(new java.awt.Color(255, 255, 255));
        N2.setText("2");
        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });
        getContentPane().add(N2);
        N2.setBounds(90, 140, 60, 60);

        N3.setBackground(new java.awt.Color(0, 0, 0));
        N3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        N3.setForeground(new java.awt.Color(255, 255, 255));
        N3.setText("3");
        N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N3ActionPerformed(evt);
            }
        });
        getContentPane().add(N3);
        N3.setBounds(150, 140, 60, 60);

        N6.setBackground(new java.awt.Color(0, 0, 0));
        N6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        N6.setForeground(new java.awt.Color(255, 255, 255));
        N6.setText("6");
        N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N6ActionPerformed(evt);
            }
        });
        getContentPane().add(N6);
        N6.setBounds(150, 200, 60, 60);

        N5.setBackground(new java.awt.Color(0, 0, 0));
        N5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        N5.setForeground(new java.awt.Color(255, 255, 255));
        N5.setText("5");
        N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N5ActionPerformed(evt);
            }
        });
        getContentPane().add(N5);
        N5.setBounds(90, 200, 60, 60);

        N4.setBackground(new java.awt.Color(0, 0, 0));
        N4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        N4.setForeground(new java.awt.Color(255, 255, 255));
        N4.setText("4");
        N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N4ActionPerformed(evt);
            }
        });
        getContentPane().add(N4);
        N4.setBounds(30, 200, 60, 60);

        N9.setBackground(new java.awt.Color(0, 0, 0));
        N9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        N9.setForeground(new java.awt.Color(255, 255, 255));
        N9.setText("9");
        N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N9ActionPerformed(evt);
            }
        });
        getContentPane().add(N9);
        N9.setBounds(150, 260, 60, 60);

        N8.setBackground(new java.awt.Color(0, 0, 0));
        N8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        N8.setForeground(new java.awt.Color(255, 255, 255));
        N8.setText("8");
        N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N8ActionPerformed(evt);
            }
        });
        getContentPane().add(N8);
        N8.setBounds(90, 260, 60, 60);

        N7.setBackground(new java.awt.Color(0, 0, 0));
        N7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        N7.setForeground(new java.awt.Color(255, 255, 255));
        N7.setText("7");
        N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N7ActionPerformed(evt);
            }
        });
        getContentPane().add(N7);
        N7.setBounds(30, 260, 60, 60);

        N0.setBackground(new java.awt.Color(0, 0, 0));
        N0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N0.setForeground(new java.awt.Color(255, 255, 255));
        N0.setText("0");
        N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0ActionPerformed(evt);
            }
        });
        getContentPane().add(N0);
        N0.setBounds(30, 320, 60, 60);

        btnLimp.setBackground(new java.awt.Color(51, 51, 51));
        btnLimp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimp.setForeground(new java.awt.Color(255, 255, 255));
        btnLimp.setText("C");
        btnLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimp);
        btnLimp.setBounds(210, 140, 60, 30);

        Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\calcImg.png")); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 300, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        PrimerNumero = Double.parseDouble(Pantalla.getText());
        Pantalla.setText("  ");
        Operador = "+";
    }//GEN-LAST:event_btnSumaActionPerformed

    private void N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0ActionPerformed
        String Numero = Pantalla.getText() + N0.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N0ActionPerformed

    private void btnLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpActionPerformed
        Pantalla.setText("  ");
    }//GEN-LAST:event_btnLimpActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        SegundoNumero = Double.parseDouble(Pantalla.getText());
        
        if(Operador.equals("+")) {
            Resultado = PrimerNumero + SegundoNumero;
            Pantalla.setText(Double.toString(Resultado));
            
        } else if(Operador.equals("-")) {
            Resultado = PrimerNumero - SegundoNumero;
            Pantalla.setText(Double.toString(Resultado));
            
        }else if(Operador.equals("*")) {
            Resultado = PrimerNumero * SegundoNumero;
            Pantalla.setText(Double.toString(Resultado));
            
        }else if(Operador.equals("/")) {
            Resultado = PrimerNumero / SegundoNumero;
            Pantalla.setText(Double.toString(Resultado));}
    }//GEN-LAST:event_btnIgualActionPerformed

    private void PantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaActionPerformed

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
        String Numero = Pantalla.getText() + N1.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N1ActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
        String Numero = Pantalla.getText() + N2.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N2ActionPerformed

    private void N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N3ActionPerformed
        String Numero = Pantalla.getText() + N3.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N3ActionPerformed

    private void N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N4ActionPerformed
        String Numero = Pantalla.getText() + N4.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N4ActionPerformed

    private void N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N5ActionPerformed
        String Numero = Pantalla.getText() + N5.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N5ActionPerformed

    private void N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N6ActionPerformed
        String Numero = Pantalla.getText() + N6.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N6ActionPerformed

    private void N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N7ActionPerformed
        String Numero = Pantalla.getText() + N7.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N7ActionPerformed

    private void N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N8ActionPerformed
        String Numero = Pantalla.getText() + N8.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N8ActionPerformed

    private void N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N9ActionPerformed
        String Numero = Pantalla.getText() + N9.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N9ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        String Numero = Pantalla.getText() + btnPunto.getText();
        Pantalla.setText(Numero);    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        PrimerNumero = Double.parseDouble(Pantalla.getText());
        Pantalla.setText("  ");
        Operador = "-";
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        PrimerNumero = Double.parseDouble(Pantalla.getText());
        Pantalla.setText("  ");
        Operador = "/";
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        PrimerNumero = Double.parseDouble(Pantalla.getText());
        Pantalla.setText("  ");
        Operador = "*";
    }//GEN-LAST:event_btnMultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton N0;
    private javax.swing.JButton N1;
    private javax.swing.JButton N2;
    private javax.swing.JButton N3;
    private javax.swing.JButton N4;
    private javax.swing.JButton N5;
    private javax.swing.JButton N6;
    private javax.swing.JButton N7;
    private javax.swing.JButton N8;
    private javax.swing.JButton N9;
    private javax.swing.JTextField Pantalla;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimp;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    // End of variables declaration//GEN-END:variables
}
